import {
  STAGE_ENUM,
  INTENSITY_ENUM,
  EXTREMITY_ENUM,
  ACT_WITH_ENUM,
  ACT_ON_ENUM,
} from "./enums.js";
import { gameSaveState } from "./gamestate.js";

export function initGameSettings() {
  fillSettingsStage(); // Fill settings section
  fillSettingsIntensity(); // Fill settings section
  fillSettingsExtremity(); // Fill settings section
  fillSettingsActWith();
  fillSettingsActOn();
}

/* ---------- 1) GENERIEKE BUILDER ---------- */
function buildSettingsCollection(enumObj, defaultEnabled = true) {
  const out = {};
  for (const [key, value] of Object.entries(enumObj)) {
    out[key] = { value, enabled: defaultEnabled };
  }
  return out;
}

/* Zorg dat window.GAME.settings[prop] bestaat (lazy init) */
function ensureSettingsCollection(prop, enumObj, defaultEnabled = true) {
  window.GAME = window.GAME || {};
  window.GAME.settings = window.GAME.settings || {};
  if (!window.GAME.settings[prop]) {
    window.GAME.settings[prop] = buildSettingsCollection(
      enumObj,
      defaultEnabled
    );
  }
  return window.GAME.settings[prop];
}

/* ---------- TASK-SETTING REFERENTIE CHECK ---------- */
function isSettingReferenced(prop) {
  // Check of ten minste één task in het model deze setting expliciet gebruikt
  // (dwz conditions[prop] bestaat en heeft lengte > 0)
  const cats = Object.values(TASKS_MODEL || {});
  for (const cat of cats) {
    const tasks = cat?.tasks || [];
    for (const t of tasks) {
      const arr = t?.conditions?.[prop];
      if (Array.isArray(arr) && arr.length > 0) return true;
    }
  }
  return false;
}

/* ---------- GENERIEKE RENDERER ---------- */
/**
 * Render een lijst toggles op basis van een enum/collectie in game settings.
 * @param {Object} opts
 *   - targetId:  id van de container
 *   - prop:      key in window.GAME.settings (bv. "stage", "intensity", "extremity", "act")
 *   - enumObj:   het ENUM object (bv. STAGE_ENUM)
 */
function fillSettingsList({ targetId, prop, enumObj }) {
  const root = document.getElementById(targetId);
  if (!root) return;

  // NIEUW: als geen enkele task deze setting gebruikt, niet renderen en defaults uitzetten
  if (!isSettingReferenced(prop)) {
    const coll = ensureSettingsCollection(prop, enumObj, false);
    for (const k of Object.keys(coll)) {
      coll[k].enabled = false;
    }
    return; // niets tonen in de GUI
  }

  const coll = ensureSettingsCollection(prop, enumObj, true);

  const existing = root.querySelector("#AutoGenerated");
  if (existing) existing.remove();

  const Wrap = document.createElement("div");
  Wrap.className = "col small";
  Wrap.id = "AutoGenerated";

  for (const [key, cfg] of Object.entries(coll)) {
    const { value, enabled } = cfg;

    const row = document.createElement("label");
    row.className = "row grid3 list";

    const id = `${prop}_${key.toLowerCase()}`;

    const cb = document.createElement("input");
    cb.type = "checkbox";
    cb.id = id;
    cb.checked = !!enabled;
    cb.setAttribute("data-key", key); // generiek attribuut
    cb.setAttribute("data-prop", prop); // zodat 1 handler alles kan verwerken

    const label = document.createElement("label");
    label.setAttribute("for", id);
    label.setAttribute("data-i18n-auto", `${value}.name`);

    const desc = document.createElement("span");
    desc.className = "muted";
    desc.setAttribute("data-i18n-auto", `${value}.descShort`);

    row.appendChild(cb);
    row.appendChild(label);
    row.appendChild(desc);
    Wrap.appendChild(row);

    cb.addEventListener("change", (e) => {
      const k = e.currentTarget.getAttribute("data-key");
      const p = e.currentTarget.getAttribute("data-prop");
      if (!window.GAME?.settings?.[p]?.[k]) return;
      window.GAME.settings[p][k].enabled = e.currentTarget.checked;
      gameSaveState();
    });
  }

  root.append(Wrap);
}

/* ---------- CONVENIENCE CALLS ---------- */
/* Gebruik deze waar je eerder de specifieke functies riep: */
// Stages
function fillSettingsStage(targetId = "settings_stage") {
  fillSettingsList({ targetId, prop: "stage", enumObj: STAGE_ENUM });
}

export function getSettingStages() {
  return buildSettingsCollection(STAGE_ENUM, true);
}

// Intensity
function fillSettingsIntensity(targetId = "settings_intensity") {
  fillSettingsList({ targetId, prop: "intensity", enumObj: INTENSITY_ENUM });
}

export function getSettingIntensity() {
  return buildSettingsCollection(INTENSITY_ENUM, true);
}

// Extremity
function fillSettingsExtremity(targetId = "settings_extremity") {
  fillSettingsList({ targetId, prop: "extremity", enumObj: EXTREMITY_ENUM });
}

export function getSettingExtremity() {
  return buildSettingsCollection(EXTREMITY_ENUM, true);
}

// Act With
function fillSettingsActWith(targetId = "settings_act_with") {
  fillSettingsList({ targetId, prop: "act_with", enumObj: ACT_WITH_ENUM });
}

export function getSettingActWith() {
  return buildSettingsCollection(ACT_WITH_ENUM, true);
}

// Act On
function fillSettingsActOn(targetId = "settings_act_on") {
  fillSettingsList({ targetId, prop: "act_on", enumObj: ACT_ON_ENUM });
}

export function getSettingActOn() {
  return buildSettingsCollection(ACT_ON_ENUM, true);
}