import {
  STAGE_ENUM,
  INTENSITY_ENUM,
  EXTREMITY_ENUM,
  ACT_WITH_ENUM,
  ACT_ON_ENUM,
} from "./enums.js";
import { gameSaveState } from "./gamestate.js";
import { getTasksModel } from "./tasks.js";
import { setI18n } from "./lang_i18n.js";

export function initGameSettings() {
  fillSettingsGeneral();
  fillSettingsStage(); // Fill settings section
  fillSettingsIntensity(); // Fill settings section
  fillSettingsExtremity(); // Fill settings section
  fillSettingsActWith();
  fillSettingsActOn();
}

/* ---------- 1) GENERIEKE BUILDER ---------- */
function buildSettingsCollection(enumObj, defaultEnabled = true) {
  const out = {};
  for (const [key, value] of Object.entries(enumObj)) {
    out[key] = { value, enabled: defaultEnabled };
  }
  return out;
}

/* Zorg dat window.GAME.settings[prop] bestaat (lazy init) */
function ensureSettingsCollection(prop, enumObj, defaultEnabled = true) {
  window.GAME = window.GAME || {};
  window.GAME.settings = window.GAME.settings || {};
  if (!window.GAME.settings[prop]) {
    window.GAME.settings[prop] = buildSettingsCollection(
      enumObj,
      defaultEnabled
    );
  }
  return window.GAME.settings[prop];
}

/* ---------- TASK-SETTING REFERENTIE CHECK ---------- */
function getReferencedEnumValues(prop) {
  const used = new Set();
  const cats = Object.values(getTasksModel() || {});
  for (const cat of cats) {
    const tasks = cat?.tasks || [];
    for (const t of tasks) {
      const arr = t?.conditions?.[prop];
      if (Array.isArray(arr) && arr.length > 0) {
        for (const v of arr) used.add(v); // exacte enum-waarden die in conditions gebruikt worden
      }
    }
  }
  return used; // Set met bv. "ACT_WITH_ENUM.HAND", "ACT_WITH_ENUM.MOUTH", ...
}

/* ---------- PRIMITIVE SETTINGS HELPERS ---------- */
function ensurePrimitiveSetting(key, defaultValue) {
  window.GAME = window.GAME || {};
  window.GAME.settings = window.GAME.settings || {};
  if (window.GAME.settings[key] === undefined) {
    window.GAME.settings[key] = defaultValue;
  }
  return window.GAME.settings[key];
}

/* ---------- GENERAL SETTINGS UI ---------- */
function fillSettingsGeneral(targetId = "settings_general") {
  const root = document.getElementById(targetId);
  if (!root) return;

  const dices       = ensurePrimitiveSetting("dices",       5);
  const rolls       = ensurePrimitiveSetting("rolls",       3);
  const score       = ensurePrimitiveSetting("score",       3);
  const secretTasks = ensurePrimitiveSetting("secretTasks", true);

  const existing = root.querySelector("#AutoGeneratedGeneral");
  if (existing) existing.remove();

  const wrap = document.createElement("div");
  wrap.className = "col small";
  wrap.id = "AutoGeneratedGeneral";

  // label + desc rechts, input links
  const makeRow = (id, baseI18nKey, inputEl) => {
    const row = document.createElement("label");
    row.className = "row grid3 list";

    inputEl.id = id;

    const lab = document.createElement("label");
    lab.setAttribute("for", id);
    // lab.setAttribute("data-i18n-auto", baseI18nKey);
    setI18n(lab, baseI18nKey);

    const span = document.createElement("span");
    span.className = "muted";
    // toon de korte beschrijving
    // span.setAttribute("data-i18n-auto", `${baseI18nKey}.descShort`);
    setI18n(span, `${baseI18nKey}.descShort`);

    row.appendChild(inputEl);
    row.appendChild(lab);
    row.appendChild(span);
    wrap.appendChild(row);
  };

  // Dices (number >= 1)
  const inpDices = document.createElement("input");
  inpDices.type = "number";
  inpDices.min = "1";
  inpDices.step = "1";
  inpDices.value = dices;
  inpDices.addEventListener("input", (e) => {
    const v = Math.max(1, parseInt(e.currentTarget.value || "1", 10));
    window.GAME.settings.dices = v;
    e.currentTarget.value = v;
    gameSaveState();
  });
  makeRow("general_dices", "app.settings.general.dices", inpDices);

  // Rolls (number >= 1)
  const inpRolls = document.createElement("input");
  inpRolls.type = "number";
  inpRolls.min = "1";
  inpRolls.step = "1";
  inpRolls.value = rolls;
  inpRolls.addEventListener("input", (e) => {
    const v = Math.max(1, parseInt(e.currentTarget.value || "1", 10));
    window.GAME.settings.rolls = v;
    e.currentTarget.value = v;
    gameSaveState();
  });
  makeRow("general_rolls", "app.settings.general.rolls", inpRolls);

  // Score (number >= 1)
  const inpScore = document.createElement("input");
  inpScore.type = "number";
  inpScore.min = "1";
  inpScore.step = "1";
  inpScore.value = score;
  inpScore.addEventListener("input", (e) => {
    const v = Math.max(1, parseInt(e.currentTarget.value || "1", 10));
    window.GAME.settings.score = v;
    e.currentTarget.value = v;
    gameSaveState();
  });
  makeRow("general_score", "app.settings.general.score", inpScore);

  // Secret Tasks (checkbox)
  const cbSecret = document.createElement("input");
  cbSecret.type = "checkbox";
  cbSecret.checked = !!secretTasks;
  cbSecret.addEventListener("change", (e) => {
    window.GAME.settings.secretTasks = e.currentTarget.checked;
    gameSaveState();
  });
  makeRow("general_secretTasks", "app.settings.general.secretTasks", cbSecret);

  root.appendChild(wrap);
}


/* ---------- GENERIEKE RENDERER ---------- */
/**
 * Render een lijst toggles op basis van een enum/collectie in game settings.
 * @param {Object} opts
 *   - targetId:  id van de container
 *   - prop:      key in window.GAME.settings (bv. "stage", "intensity", "extremity", "act")
 *   - enumObj:   het ENUM object (bv. STAGE_ENUM)
 */
function fillSettingsList({ targetId, prop, enumObj }) {
  const root = document.getElementById(targetId);
  if (!root) return;

  // init met alles uit (false), we zetten alleen gebruikte opties aan + renderen die
  const coll = ensureSettingsCollection(prop, enumObj, false);

  // bepaal exact welke enum-values ergens in tasks[ ].conditions[prop] voorkomen
  const referenced = getReferencedEnumValues(prop);

  // als niets refereert -> niets renderen (GUI overslaan)
  if (referenced.size === 0) {
    root.remove();
    return;
  }

  const existing = root.querySelector("#AutoGenerated");
  if (existing) existing.remove();

  const Wrap = document.createElement("div");
  Wrap.className = "col small";
  Wrap.id = "AutoGenerated";

  for (const [key, cfg] of Object.entries(coll)) {
    const { value } = cfg;

    if (!referenced.has(value)) {
      coll[key].enabled = false; // expliciet uit
      continue; // niet tonen in GUI
    }
    coll[key].enabled = true; // standaard aan voor gebruikte enum-waarde

    const row = document.createElement("label");
    row.className = "row grid3 list";

    const id = `${prop}_${key.toLowerCase()}`;

    const cb = document.createElement("input");
    cb.type = "checkbox";
    cb.id = id;
    cb.checked = true; // gebruikt ⇒ aan
    cb.setAttribute("data-key", key); // generiek attribuut
    cb.setAttribute("data-prop", prop); // zodat 1 handler alles kan verwerken

    const label = document.createElement("label");
    label.setAttribute("for", id);
    // label.setAttribute("data-i18n-auto", `${value}.name`);
    setI18n(label, `${value}.name`);

    const desc = document.createElement("span");
    desc.className = "muted";
    // desc.setAttribute("data-i18n-auto", `${value}.descShort`);
    setI18n(desc, `${value}.descShort`);

    row.appendChild(cb);
    row.appendChild(label);
    row.appendChild(desc);
    Wrap.appendChild(row);

    cb.addEventListener("change", (e) => {
      const k = e.currentTarget.getAttribute("data-key");
      const p = e.currentTarget.getAttribute("data-prop");
      if (!window.GAME?.settings?.[p]?.[k]) return;
      window.GAME.settings[p][k].enabled = e.currentTarget.checked;
      gameSaveState();
    });
  }

  root.append(Wrap);
  gameSaveState();
}

/* ---------- CONVENIENCE CALLS ---------- */
/* Gebruik deze waar je eerder de specifieke functies riep: */
// Stages
function fillSettingsStage(targetId = "settings_stage") {
  fillSettingsList({ targetId, prop: "stage", enumObj: STAGE_ENUM });
}

export function getSettingStages() {
  return buildSettingsCollection(STAGE_ENUM, false);
}

// Intensity
function fillSettingsIntensity(targetId = "settings_intensity") {
  fillSettingsList({ targetId, prop: "intensity", enumObj: INTENSITY_ENUM });
}

export function getSettingIntensity() {
  return buildSettingsCollection(INTENSITY_ENUM, false);
}

// Extremity
function fillSettingsExtremity(targetId = "settings_extremity") {
  fillSettingsList({ targetId, prop: "extremity", enumObj: EXTREMITY_ENUM });
}

export function getSettingExtremity() {
  return buildSettingsCollection(EXTREMITY_ENUM, false);
}

// Act With
function fillSettingsActWith(targetId = "settings_act_with") {
  fillSettingsList({ targetId, prop: "act_with", enumObj: ACT_WITH_ENUM });
}

export function getSettingActWith() {
  return buildSettingsCollection(ACT_WITH_ENUM, false);
}

// Act On
function fillSettingsActOn(targetId = "settings_act_on") {
  fillSettingsList({ targetId, prop: "act_on", enumObj: ACT_ON_ENUM });
}

export function getSettingActOn() {
  return buildSettingsCollection(ACT_ON_ENUM, false);
}