import {
  SEX_ENUM,
  STAGE_ENUM,
  INTENSITY_ENUM,
  EXTREMITY_ENUM,
  ACT_ON_ENUM,
  ACT_WITH_ENUM,
  PLAYERTARGET_ENUM,
} from "../enums.js";

export const tasks_undress_other_self = [
  {
    enabled: true,
    id: `undress_other_self.headwear`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.headwear.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "headwear" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INNOCENT",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.accessories_glasses`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.accessories_glasses.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "accessories_glasses" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INNOCENT",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.accessories_neck`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.accessories_neck.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "accessories_neck" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INNOCENT",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.accessories_arm`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.accessories_arm.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "accessories_arm" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INNOCENT",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.jacket`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.jacket.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "jacket" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INNOCENT",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.sweater`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.sweater.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "sweater" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.shirt`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.shirt.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "shirt" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.undershirt`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.undershirt.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "undershirt" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.bra`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.bra.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "bra" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "SENSUAL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.pants`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.pants.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "pants" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.leggings`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.leggings.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "leggings" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.underwear`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.underwear.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "underwear" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "SENSUAL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.shoes`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.shoes.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "shoes" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INNOCENT",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `undress_other_self.socks`,
    instructionKey: "TASK.Undress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.socks.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.remove", slot: "loser", item: "socks" },
      {
        type: "weight.category",
        category: "undress_other_self",
        op: "mult",
        value: 0.95,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "INTIMATE",
        op: "mult",
        value: 1.1,
      },
      {
        type: "weight.game",
        bucket: "stage",
        match: "PLAYFUL",
        op: "mult",
        value: 0.9,
      },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
];
