import {
  SEX_ENUM,
  STAGE_ENUM,
  INTENSITY_ENUM,
  EXTREMITY_ENUM,
  ACT_ON_ENUM,
  ACT_WITH_ENUM,
  PLAYERTARGET_ENUM,
} from "../enums.js";

export const tasks_dress_other_self = [
  {
    enabled: true,
    id: `dress_other_self.headwear`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.headwear.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "headwear" }],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.accessories_glasses`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.accessories_glasses.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.add", slot: "loser", item: "accessories_glasses" },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.accessories_neck`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.accessories_neck.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [
      { type: "clothing.add", slot: "loser", item: "accessories_neck" },
    ],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.accessories_arm`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.accessories_arm.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "accessories_arm" }],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.jacket`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.jacket.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "jacket" }],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.sweater`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.sweater.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "sweater" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.shirt`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.shirt.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "shirt" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.undershirt`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.undershirt.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "undershirt" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.bra`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.bra.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "bra" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.pants`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.pants.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "pants" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.leggings`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.leggings.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "leggings" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.underwear`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.underwear.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "underwear" }],
    flags: {
      checkPreferSex: true,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.shoes`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.shoes.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "shoes" }],
    flags: {
      checkPreferSex: false,
    },
  },
  {
    enabled: true,
    id: `dress_other_self.socks`,
    instructionKey: "TASK.Dress.Other_Self.Public",
    instruction_args: {
      clothing: "{clothes.socks.name}",
      loser: "Loser",
      winner1: "Winner1",
    },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Dress.Other_Self.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.add", slot: "loser", item: "socks" }],
    flags: {
      checkPreferSex: false,
    },
  },
];
