import {
  SEX_ENUM,
  STAGE_ENUM,
  INTENSITY_ENUM,
  EXTREMITY_ENUM,
  ACT_ON_ENUM,
  ACT_WITH_ENUM,
  PLAYERTARGET_ENUM,
} from "../enums.js";

export const tasks_undress_other = [
  {
    id: `undress_other.headwear`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.headwear.name", loser: "Loser", winner1: "Winner1" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "headwear" }],
  },
  {
    id: `undress_other.accessories_glasses`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.accessories_glasses.name", p0: "PLAYER0" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "accessories_glasses" }],
  },
  {
    id: `undress_other.accessories_neck`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.accessories_neck.name", p0: "PLAYER0" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "accessories_neck" }],
  },
  {
    id: `undress_other.accessories_arm`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.accessories_arm.name", p0: "PLAYER0" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "accessories_arm" }],
  },
  {
    id: `undress_other.jacket`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.jacket.name", p0: "PLAYER0" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "jacket" }],
  },
  {
    id: `undress_other.sweater`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.sweater.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "sweater" }],
  },
  {
    id: `undress_other.shirt`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.shirt.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "shirt" }],
  },
  {
    id: `undress_other.undershirt`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.undershirt.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "undershirt" }],
  },
  {
    id: `undress_other.bra`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.bra.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "bra" }],
  },
  {
    id: `undress_other.pants`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.pants.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "pants" }],
  },
  {
    id: `undress_other.leggings`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.leggings.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "leggings" }],
  },
  {
    id: `undress_other.underwear`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.underwear.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "underwear" }],
  },
  {
    id: `undress_other.shoes`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.shoes.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "shoes" }],
  },
  {
    id: `undress_other.socks`,
    instructionKey: "TASK.Undress.Other.Public",
    instruction_args: { clothing: "clothes.socks.name", p0: "PLAYER0" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: null,
      },
      {
        slot: "winner1",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.winner,
        sex: [],
        secretInstructionKey: "TASK.Undress.Other.Secret.Winner1",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "socks" }],
  },
];
