import {
  SEX_ENUM,
  STAGE_ENUM,
  INTENSITY_ENUM,
  EXTREMITY_ENUM,
  ACT_ON_ENUM,
  ACT_WITH_ENUM,
  PLAYERTARGET_ENUM,
} from "../enums.js";

export const tasks_undress_self = [
  {
    id: `undress_self.headwear`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.headwear.name", loser: "Loser" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "headwear" }],
  },
  {
    id: `undress_self.accessories_glasses`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.accessories_glasses.name", loser: "Loser" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "accessories_glasses" }],
  },
  {
    id: `undress_self.accessories_neck`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.accessories_neck.name", loser: "Loser" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "accessories_neck" }],
  },
  {
    id: `undress_self.accessories_arm`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.accessories_arm.name", loser: "Loser" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "accessories_arm" }],
  },
  {
    id: `undress_self.jacket`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.jacket.name", loser: "Loser" },
    conditions: {
      stage: [],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "jacket" }],
  },
  {
    id: `undress_self.sweater`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.sweater.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "sweater" }],
  },
  {
    id: `undress_self.shirt`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.shirt.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "shirt" }],
  },
  {
    id: `undress_self.undershirt`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.undershirt.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "undershirt" }],
  },
  {
    id: `undress_self.bra`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.bra.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "bra" }],
  },
  {
    id: `undress_self.pants`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.pants.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "pants" }],
  },
  {
    id: `undress_self.leggings`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.leggings.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "leggings" }],
  },
  {
    id: `undress_self.underwear`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.underwear.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.INTIMATE],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "underwear" }],
  },
  {
    id: `undress_self.shoes`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.shoes.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.INNOCENT],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "shoes" }],
  },
  {
    id: `undress_self.socks`,
    instructionKey: "TASK.Undress.Self.Public",
    instruction_args: { clothing: "clothes.socks.name", loser: "Loser" },
    conditions: {
      stage: [STAGE_ENUM.PLAYFUL],
      intensity: [],
      extremity: [],
      act_with: [],
      act_on: [],
    },
    participants: [
      {
        slot: "loser",
        player: null,
        players: [],
        target: PLAYERTARGET_ENUM.loser,
        sex: [],
        secretInstructionKey: "TASK.Undress.Self.Secret",
      },
    ],
    effects: [{ type: "clothing.remove", slot: "loser", item: "socks" }],
  },
];
